### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DaanVink**
disambiguation of README.md

### CODE REVIEW

**Comment by Skayo** [comment]
How about adding a `ISSUE_TEMPLATE.md`?

**Comment by DaanVink** [comment]
@Skayo did you mean to add this as a comment to my pull request, or as an issue/suggestion?

**Comment by Skayo** [comment]
A suggestion. Since you already started this pull request you could add this too.

**Comment by DFoxinator** [comment]
Thanks! And an issue template would be awesome, great idea @Skayo.

**Pull request merged**
